### ISSUE TITLE
KYSSSS NIGGAAAAAa DEATH SNIPER ON TOP U SUCK MY COCK

### ISSUE THREAD

**Issue by AndrewKys** [worpiton/self-bot-searcher#15]
https://discord.gg/deathsniper https://discord.gg/deathsniper https://discord.gg/deathsniper https://discord.gg/deathsniper https://discord.gg/deathsniper https://discord.gg/deathsniper https://discord.gg/deathsniper https://discord.gg/deathsniper https://discord.gg/deathsniper https://discord.gg/deathsniper https://discord.gg/deathsniper https://discord.gg/deathsniper https://discord.gg/deathsniper https://discord.gg/deathsniper https://discord.gg/deathsniper https://discord.gg/deathsniper

**Comment by worpiton** [comment]
cry about it
