### ISSUE TITLE
HOW IT S LIKE TO BE FATHERLESS 

### ISSUE THREAD

**Issue by AndrewKys** [worpiton/self-bot-searcher#28]
https://discord.gg/deathsniper https://discord.gg/deathsniper https://discord.gg/deathsniper https://discord.gg/deathsniper https://discord.gg/deathsniper https://discord.gg/deathsniper https://discord.gg/deathsniper https://discord.gg/deathsniper https://discord.gg/deathsniper https://discord.gg/deathsniper https://discord.gg/deathsniper https://discord.gg/deathsniper https://discord.gg/deathsniper https://discord.gg/deathsniper https://discord.gg/deathsniper https://discord.gg/deathsniper https://discord.gg/deathsniper

**Comment by worpiton** [comment]
cry about it
