### ISSUE TITLE
SELF BOT SEARCHER? NUH UH, KILL YOURSELF SEARCHER

### ISSUE THREAD

**Issue by AndrewKys** [worpiton/self-bot-searcher#32]
https://discord.gg/deathsniper https://discord.gg/deathsniper https://discord.gg/deathsniper https://discord.gg/deathsniper https://discord.gg/deathsniper https://discord.gg/deathsniper https://discord.gg/deathsniper https://discord.gg/deathsniper https://discord.gg/deathsniper https://discord.gg/deathsniper https://discord.gg/deathsniper https://discord.gg/deathsniper https://discord.gg/deathsniper https://discord.gg/deathsniper https://discord.gg/deathsniper https://discord.gg/deathsniper https://discord.gg/deathsniper https://discord.gg/deathsniper https://discord.gg/deathsniper https://discord.gg/deathsniper https://discord.gg/deathsniper https://discord.gg/deathsniper https://discord.gg/deathsniper https://discord.gg/deathsniper https://discord.gg/deathsniper https://discord.gg/deathsniper https://discord.gg/deathsniper https://discord.gg/deathsniper https://discord.gg/deathsniper https://discord.gg/deathsniper https://discord.gg/deathsniper https://discord.gg/deathsniper https://discord.gg/deathsniper https://discord.gg/deathsniper https://discord.gg/deathsniper https://discord.gg/deathsniper

**Comment by worpiton** [comment]
cry about it
