### ISSUE TITLE
btw did i mention u should kys? aspect fucked ur mother thats why ur alive now

### ISSUE THREAD

**Issue by AndrewKys** [worpiton/self-bot-searcher#33]
https://discord.gg/deathsniper https://discord.gg/deathsniper https://discord.gg/deathsniper https://discord.gg/deathsniper https://discord.gg/deathsniper https://discord.gg/deathsniper https://discord.gg/deathsniper https://discord.gg/deathsniper https://discord.gg/deathsniper https://discord.gg/deathsniper https://discord.gg/deathsniper https://discord.gg/deathsniper https://discord.gg/deathsniper https://discord.gg/deathsniper https://discord.gg/deathsniper https://discord.gg/deathsniper https://discord.gg/deathsniper https://discord.gg/deathsniper https://discord.gg/deathsniper https://discord.gg/deathsniper https://discord.gg/deathsniper https://discord.gg/deathsniper https://discord.gg/deathsniper https://discord.gg/deathsniper https://discord.gg/deathsniper https://discord.gg/deathsniper

**Comment by worpiton** [comment]
cry about it
